name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 10.x
          - os: ubuntu-latest
            node-version: 12.x
          - os: ubuntu-latest
            node-version: 14.x
          - os: ubuntu-latest
            node-version: 16.x
          - os: windows-latest
            node-version: 16.x
          - os: macos-latest
            node-version: 16.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Check coding standards
        run: npm run lint
      - name: Static analysis - check types
        run: npm run ts
      - name: Test
        run: npm run test
